// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE
'use strict';

var Css = require("bs-css/src/Css.js");
var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var Theme = require("./Theme.bs.js");
var React = require("react");
var Colors = require("./Colors.bs.js");
var MaterialUi = require("@jsiebern/bs-material-ui/src/MaterialUi.bs.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var MenuSvg = require("../assets/img/menu.svg");
var LogoSolidSvg = require("../assets/img/logo-solid.svg");

function text(prim) {
  return prim;
}

var component = ReasonReact.reducerComponent("Layout");

var flex_ = Css.style(/* :: */[
      Css.flex(1),
      /* [] */0
    ]);

var appBar = Css.style(/* :: */[
      Css.backgroundColor(Colors.white),
      /* :: */[
        Css.boxShadow(/* None */0, /* None */0, /* None */0, /* None */0, /* None */0, Colors.white),
        /* [] */0
      ]
    ]);

var container = Css.style(/* :: */[
      Css.flexGrow(1),
      /* :: */[
        Css.width(/* `percent */[
              -119887163,
              100.0
            ]),
        /* :: */[
          Css.height(/* `percent */[
                -119887163,
                100.0
              ]),
          /* :: */[
            Css.margin(Css.px(0)),
            /* :: */[
              Css.overflow(Css.hidden),
              /* [] */0
            ]
          ]
        ]
      ]
    ]);

var grid = Css.style(/* :: */[
      Css.width(/* `percent */[
            -119887163,
            100.0
          ]),
      /* :: */[
        Css.height(/* `calc */[
              -1044768619,
              /* tuple */[
                /* sub */5745024,
                /* `percent */[
                  -119887163,
                  100.0
                ],
                /* `px */[
                  25096,
                  64
                ]
              ]
            ]),
        /* :: */[
          Css.margin(Css.px(0)),
          /* :: */[
            Css.overflowY(Css.auto),
            /* [] */0
          ]
        ]
      ]
    ]);

var drawer = Css.style(/* :: */[
      Css.width(/* `px */[
            25096,
            440
          ]),
      /* :: */[
        Css.flex(1),
        /* [] */0
      ]
    ]);

var Styles = /* module */[
  /* flex_ */flex_,
  /* appBar */appBar,
  /* container */container,
  /* grid */grid,
  /* drawer */drawer
];

function make(drawer$1, children) {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function (param) {
      var send = param[/* send */4];
      return ReasonReact.element(/* None */0, /* None */0, MaterialUi.MuiThemeProvider[/* make */0](/* None */0, /* None */0, /* `ObjectGeneric */[
                      -317959944,
                      Theme.toJsUnsafe(Theme.theme)
                    ], /* array */[ReasonReact.element(/* None */0, /* None */0, MaterialUi.CssBaseline[/* make */0](/* array */[React.createElement("div", {
                                      className: container
                                    }, drawer$1 ? ReasonReact.element(/* None */0, /* None */0, MaterialUi.AppBar[/* make */5](/* Some */[appBar], /* None */0, /* Some */[/* Static */982536398], /* None */0, /* None */0, /* None */0, /* None */0, /* array */[
                                                ReasonReact.element(/* None */0, /* None */0, MaterialUi.Toolbar[/* make */1](/* None */0, /* None */0, /* None */0, /* array */[
                                                          React.createElement("img", {
                                                                alt: "logo",
                                                                src: LogoSolidSvg
                                                              }),
                                                          React.createElement("div", {
                                                                className: flex_
                                                              }),
                                                          ReasonReact.element(/* None */0, /* None */0, MaterialUi.IconButton[/* make */3](/* None */0, /* Some */[/* Inherit */-72987685], /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* Some */[(function () {
                                                                        return Curry._1(send, /* OpenDrawer */0);
                                                                      })], /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* array */[React.createElement("img", {
                                                                          alt: "menu",
                                                                          src: MenuSvg
                                                                        })]))
                                                        ])),
                                                ReasonReact.element(/* None */0, /* None */0, MaterialUi.Drawer[/* make */7](/* Some */[/* Right */-57574468], /* None */0, /* None */0, /* None */0, /* Some */[(function () {
                                                              return Curry._1(send, /* CloseDrawer */1);
                                                            })], /* Some */[param[/* state */2][/* open_ */0]], /* None */0, /* None */0, Theme.toJsUnsafe(Theme.theme), /* None */0, /* Some */[/* Temporary */-103274127], /* None */0, /* array */[React.createElement("div", {
                                                                className: drawer,
                                                                role: "button",
                                                                tabIndex: 0,
                                                                onClick: (function () {
                                                                    return Curry._1(send, /* CloseDrawer */1);
                                                                  })
                                                              }, drawer$1[0])]))
                                              ])) : React.createElement("div", undefined), ReasonReact.element(/* None */0, /* None */0, MaterialUi.Grid[/* make */23](/* None */0, /* None */0, /* Some */[grid], /* None */0, /* Some */[/* true */1], /* Some */[/* Row */4102650], /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* Some */[/* V24 */3], /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* array */[children])))]))]));
    });
  newrecord[/* initialState */10] = (function () {
      return /* record */[/* open_ : false */0];
    });
  newrecord[/* reducer */12] = (function (action, _) {
      if (action !== 0) {
        return /* Update */Block.__(0, [/* record */[/* open_ : false */0]]);
      } else {
        return /* Update */Block.__(0, [/* record */[/* open_ : true */1]]);
      }
    });
  return newrecord;
}

exports.text = text;
exports.component = component;
exports.Styles = Styles;
exports.make = make;
/* component Not a pure module */
