// Generated by BUCKLESCRIPT VERSION 3.0.0, PLEASE EDIT WITH CARE
'use strict';

var Css = require("bs-css/src/Css.js");
var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var Theme = require("./Theme.bs.js");
var React = require("react");
var Colors = require("./Colors.bs.js");
var MaterialUi = require("@jsiebern/bs-material-ui/src/MaterialUi.bs.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var MenuSvg = require("../assets/img/menu.svg");
var LogoSolidSvg = require("../assets/img/logo-solid.svg");
var CloseButtonSvg = require("../assets/img/close-button.svg");

var component = ReasonReact.reducerComponent("Layout");

var flex_ = Css.style(/* :: */[
      Css.flex(1),
      /* [] */0
    ]);

var appBar = Css.style(/* :: */[
      Css.backgroundColor(Colors.white),
      /* :: */[
        Css.boxShadow(/* None */0, /* None */0, /* None */0, /* None */0, /* None */0, Colors.white),
        /* [] */0
      ]
    ]);

var container = Css.style(/* :: */[
      Css.flexGrow(1),
      /* :: */[
        Css.width(/* `percent */[
              -119887163,
              100.0
            ]),
        /* :: */[
          Css.height(/* `percent */[
                -119887163,
                100.0
              ]),
          /* :: */[
            Css.margin(Css.px(0)),
            /* :: */[
              Css.overflow(Css.hidden),
              /* [] */0
            ]
          ]
        ]
      ]
    ]);

var grid = Css.style(/* :: */[
      Css.width(/* `percent */[
            -119887163,
            100.0
          ]),
      /* :: */[
        Css.height(/* `calc */[
              -1044768619,
              /* tuple */[
                /* sub */5745024,
                /* `percent */[
                  -119887163,
                  100.0
                ],
                /* `px */[
                  25096,
                  64
                ]
              ]
            ]),
        /* :: */[
          Css.margin(Css.px(0)),
          /* :: */[
            Css.overflowY(Css.auto),
            /* [] */0
          ]
        ]
      ]
    ]);

var drawer = Css.style(/* :: */[
      Css.width(/* `px */[
            25096,
            440
          ]),
      /* :: */[
        Css.flex(1),
        /* [] */0
      ]
    ]);

var modal = Css.style(/* :: */[
      Css.width(/* `vw */[
            26433,
            90.0
          ]),
      /* :: */[
        Css.height(/* `vh */[
              26418,
              90.0
            ]),
        /* :: */[
          Css.margin2(/* `vh */[
                26418,
                5.0
              ], /* `vw */[
                26433,
                5.0
              ]),
          /* :: */[
            Css.focus(/* :: */[
                  Css.outlineStyle(/* none */-922086728),
                  /* [] */0
                ]),
            /* [] */0
          ]
        ]
      ]
    ]);

var Styles = /* module */[
  /* flex_ */flex_,
  /* appBar */appBar,
  /* container */container,
  /* grid */grid,
  /* drawer */drawer,
  /* modal */modal
];

function make(drawer$1, modal$1, children) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (param) {
              var send = param[/* send */3];
              var tmp;
              if (modal$1) {
                var match = modal$1[0];
                var onClose = match[1];
                tmp = ReasonReact.element(/* None */0, /* None */0, MaterialUi.Modal[/* make */1](/* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* Some */[onClose], /* None */0, /* None */0, true, /* None */0, /* array */[ReasonReact.element(/* None */0, /* None */0, MaterialUi.Paper[/* make */1](/* Some */[modal], /* None */0, /* None */0, /* None */0, /* None */0, /* array */[
                                    ReasonReact.element(/* None */0, /* None */0, MaterialUi.Toolbar[/* make */1](/* None */0, /* None */0, /* None */0, /* array */[
                                              React.createElement("div", {
                                                    className: flex_
                                                  }),
                                              ReasonReact.element(/* None */0, /* None */0, MaterialUi.IconButton[/* make */3](/* None */0, /* Some */[/* Inherit */-72987685], /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* Some */[onClose], /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* array */[React.createElement("img", {
                                                              alt: "close",
                                                              src: CloseButtonSvg
                                                            })]))
                                            ])),
                                    match[0]
                                  ]))]));
              } else {
                tmp = null;
              }
              return ReasonReact.element(/* None */0, /* None */0, MaterialUi.MuiThemeProvider[/* make */0](/* None */0, /* None */0, /* `ObjectGeneric */[
                              -317959944,
                              Theme.toJsUnsafe(Theme.theme)
                            ], /* array */[ReasonReact.element(/* None */0, /* None */0, MaterialUi.CssBaseline[/* make */0](/* array */[React.createElement("div", {
                                              className: container
                                            }, drawer$1 ? ReasonReact.element(/* None */0, /* None */0, MaterialUi.AppBar[/* make */5](/* Some */[appBar], /* None */0, /* Some */[/* Static */982536398], /* None */0, /* None */0, /* None */0, /* None */0, /* array */[
                                                        ReasonReact.element(/* None */0, /* None */0, MaterialUi.Toolbar[/* make */1](/* None */0, /* None */0, /* None */0, /* array */[
                                                                  React.createElement("img", {
                                                                        alt: "logo",
                                                                        src: LogoSolidSvg
                                                                      }),
                                                                  React.createElement("div", {
                                                                        className: flex_
                                                                      }),
                                                                  ReasonReact.element(/* None */0, /* None */0, MaterialUi.IconButton[/* make */3](/* None */0, /* Some */[/* Inherit */-72987685], /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* Some */[(function () {
                                                                                return Curry._1(send, /* OpenDrawer */0);
                                                                              })], /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* array */[React.createElement("img", {
                                                                                  alt: "menu",
                                                                                  src: MenuSvg
                                                                                })]))
                                                                ])),
                                                        ReasonReact.element(/* None */0, /* None */0, MaterialUi.Drawer[/* make */7](/* Some */[/* Right */-57574468], /* None */0, /* None */0, /* None */0, /* Some */[(function () {
                                                                      return Curry._1(send, /* CloseDrawer */1);
                                                                    })], /* Some */[param[/* state */1][/* drawerOpen */0]], /* None */0, /* None */0, Theme.toJsUnsafe(Theme.theme), /* None */0, /* Some */[/* Temporary */-103274127], /* None */0, /* array */[React.createElement("div", {
                                                                        className: drawer,
                                                                        role: "button",
                                                                        tabIndex: 0,
                                                                        onClick: (function () {
                                                                            return Curry._1(send, /* CloseDrawer */1);
                                                                          })
                                                                      }, drawer$1[0])]))
                                                      ])) : null, tmp, ReasonReact.element(/* None */0, /* None */0, MaterialUi.Grid[/* make */23](/* None */0, /* None */0, /* Some */[grid], /* None */0, /* Some */[true], /* Some */[/* Row */4102650], /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* Some */[/* V24 */3], /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* array */[children])))]))]));
            }),
          /* initialState */(function () {
              return /* record */[/* drawerOpen */false];
            }),
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */(function (action, _) {
              if (action) {
                return /* Update */Block.__(0, [/* record */[/* drawerOpen */false]]);
              } else {
                return /* Update */Block.__(0, [/* record */[/* drawerOpen */true]]);
              }
            }),
          /* subscriptions */component[/* subscriptions */13],
          /* jsElementWrapped */component[/* jsElementWrapped */14]
        ];
}

exports.component = component;
exports.Styles = Styles;
exports.make = make;
/* component Not a pure module */
