// Generated by BUCKLESCRIPT VERSION 3.0.0, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var WebWorker = require("../ffi/WebWorker.bs.js");
var WorkerLocalStorage = require("./WorkerLocalStorage.bs.js");
var IncomeWorkerMessage = require("./IncomeWorkerMessage.bs.js");
var Income_workerBsJs = require("./Income_worker.bs.js");

var Config = /* module */[/* decodeOutgoing */IncomeWorkerMessage.decodeOutgoing];

var include = WebWorker.MakeClient([
      IncomeWorkerMessage.decodeOutgoing,
      (function () {
          return new Income_workerBsJs();
        })
    ]);

var postMessage = include[1];

function updateSession(worker) {
  return Curry._2(postMessage, worker, /* UpdateSession */[WorkerLocalStorage.readBlockstackItemsFromStorage(/* () */0)]);
}

var syncListeners = include[0];

var postMessageEncoded = include[2];

var postMessageEncodedSync = include[3];

var handleMessage = include[4];

var make = include[5];

exports.Config = Config;
exports.syncListeners = syncListeners;
exports.postMessage = postMessage;
exports.postMessageEncoded = postMessageEncoded;
exports.postMessageEncodedSync = postMessageEncodedSync;
exports.handleMessage = handleMessage;
exports.make = make;
exports.updateSession = updateSession;
/* include Not a pure module */
