// Generated by BUCKLESCRIPT VERSION 3.0.0, PLEASE EDIT WITH CARE
'use strict';

var WebWorker = require("../ffi/WebWorker.bs.js");
var PersistWorkerMessage = require("./PersistWorkerMessage.bs.js");
var Persist_workerBsJs = require("./Persist_worker.bs.js");

var Config = /* module */[/* decodeReceive */PersistWorkerMessage.decodeReceive];

var include = WebWorker.MakeClient([
      PersistWorkerMessage.decodeReceive,
      (function () {
          return new Persist_workerBsJs();
        })
    ]);

var make = include[0];

exports.Config = Config;
exports.make = make;
/* include Not a pure module */
