// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Bigi         = require("bigi");
var Blockstack   = require("blockstack");
var BitcoinjsLib = require("bitcoinjs-lib");

function sessionFromUserData(userData) {
  var match = userData.username;
  var userName = (match == null) ? "Anonymous" : match;
  return /* record */[
          /* userName */userName,
          /* appKeyPair */new BitcoinjsLib.ECPair(Bigi.fromHex(userData.appPrivateKey))
        ];
}

function getCurrentSession() {
  if (Blockstack.isUserSignedIn()) {
    var match = Blockstack.loadUserData();
    if (match == null) {
      return /* NotLoggedIn */0;
    } else {
      return /* LoggedIn */[sessionFromUserData(match)];
    }
  } else if (Blockstack.isSignInPending()) {
    return /* LoginPending */1;
  } else {
    return /* NotLoggedIn */0;
  }
}

function completeLogIn() {
  return Blockstack.handlePendingSignIn().then((function (userData) {
                return Promise.resolve(/* LoggedIn */[sessionFromUserData(userData)]);
              }));
}

function signIn() {
  Blockstack.redirectToSignIn();
  return /* LoginPending */1;
}

function signOut() {
  Blockstack.signUserOut();
  return /* NotLoggedIn */0;
}

exports.sessionFromUserData = sessionFromUserData;
exports.getCurrentSession   = getCurrentSession;
exports.completeLogIn       = completeLogIn;
exports.signIn              = signIn;
exports.signOut             = signOut;
/* bigi Not a pure module */
