// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var Js_dict = require("bs-platform/lib/js/js_dict.js");
var Belt_Array = require("bs-platform/lib/js/belt_Array.js");

function pruneNullKeys(json) {
  if (typeof json === "object" && !Array.isArray(json) && json !== null) {
    return Js_dict.fromArray(Belt_Array.keepMapU(Js_dict.entries(json), (function (param) {
                      var v = param[1];
                      var match = v === null;
                      if (match) {
                        return /* None */0;
                      } else {
                        return /* Some */[/* tuple */[
                                  param[0],
                                  v
                                ]];
                      }
                    })));
  } else if (Array.isArray(json)) {
    return Belt_Array.map(json, pruneNullKeys);
  } else {
    return json;
  }
}

exports.pruneNullKeys = pruneNullKeys;
/* Js_dict Not a pure module */
